---
- hosts: opendaylights
  gather_facts: yes
  become: yes
  become_method: sudo
  pre_tasks:
    # configure the proxy to allow access the internet via http/https for APT (package updater)
    - name: Allow update packages from the Internet via http
      raw: echo 'Acquire::http::proxy "http://193.136.128.7:3128/";' | tee /etc/apt/apt.conf.d/00proxy
    # A mininal Python is required in instances managed by Ansible
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-simplejson)
      changed_when: False
    # To operate remotely in critical files without direct user input
    - name: Remove require tty
      lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent
    # To operate remotely in critical files without direct user input
    - name: Remove require tty - alt
      lineinfile: regexp="requiretty" dest=/etc/sudoers.d/os_defaults state=absent
    # Giving permissions in sudoers for system critical files
    - name: Validate the sudoers file before saving  not to require password
      lineinfile: "dest=/etc/sudoers state=present regexp='^%ADMIN ALL=' line='%ADMIN ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"

  tasks:
    - name: jre
      apt: name={{item}} update_cache=yes state=installed
      with_items:
        - default-jre-headless

    - name: bash
      shell: echo "JAVA_HOME=/usr/lib/jvm/default-java" >> ~/.bashrc
       
    - name: Download foo.conf
      get_url:
        url: https://nexus.opendaylight.org/content/groups/public/org/opendaylight/integration/distribution-karaf/0.4.0-Beryllium/distribution-karaf-0.4.0-Beryllium.tar.gz
        dest: /home/vagrant
        validate_certs: no

    - name: tar
      shell: tar -xvf distribution-karaf-0.4.0-Beryllium.tar.gz